### PR TITLE
Towards a proper Python package

### PR DESCRIPTION
**Pull request by mromanello**
Following what sketched in [issue 4](https://github.com/dkpro/dkpro-pycas/issues/4), I have:
- re-organized as a proper python package (with setup.py, Pipfile, etc.)
- got the tests to work, after fixing some issues with path to files
- added support for `tox` which run the tests under different python versions
- added travis integration to verify the build 

I wasn't able to get it pass the tests under py27.

### CODE REVIEW

**Comment by reckart** [comment]
@mromanello WOW, great!

I have updated the commit messaged according to our conventions to include the issue number and force-pushed them into the PR. 

Btw. when you create a PR, it is highly recommendable to first create a feature branch in your repo (e.g. `feature/4-proper-python-package`), then make the changes in that branch and create a PR from that branch. This avoids potential serious confusion with the master branch in your clone and in the main repo diverging.

Could you provide us with a contributors license agreement? See https://dkpro.github.io/contributing/

**Comment by mromanello** [comment]
thanks @reckart ! I haven't contributed to many OS projects in the past, so I'm still learning how to properly do so ;-)

as for the contributor license agreement: is it ok the individual one? I'll do so right away.

**Comment by reckart** [comment]
ICLA is sufficient for us. We always consider contributions to be from the individual. Whether you need to discuss such contributions with superiors or employees is something we cannot know. The purpose of the CCLA is to have an additional layer of confirmation for contributors who do their contributions as part of a employment/contract. However, since we cannot know the circumstances of the contribution, the CCLA is optional for us. In the ICLA, you assert that you are in a position to make the contribution - that is enough for us.

**Comment by mromanello** [comment]
great! my signed ICLA is on its way towards the email address indicated in the license

**Pull request merged**
